version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    logging:
      driver: none
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    hostname: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_HOST_IP}
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  database:
    image: postgres
    restart: always
    volumes:
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: wiki_pages
      SCHEMA: public
      ROLE: docker
      AUTHENTICATOR: authenticator

  frontend:
    ports:
      - "$EXPOSE_PORT:$EXPOSE_PORT"
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        EXPOSE_PORT: $EXPOSE_PORT
    depends_on:
      - backend
    links:
      - kafka

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    links:
      - kafka
      - database
